# Generated by Django 3.2.12 on 2023-05-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todo_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-create_data']},
        ),
        migrations.AlterField(
            model_name='todo',
            name='update_data',
            field=models.DateField(auto_now=True),
        ),
    ]
